### ISSUE TITLE
Show UMTS LCID

### ISSUE THREAD

**Issue by Bryan48765** [CellMapper/Cellmapper-Site#14]

**Comment by zivan56** [comment]
It shows fine on my devices as "UMTS Cell Identity."  Are you looking for something else?

**Comment by zivan56** [comment]
Completed.

**Comment by Bryan48765** [comment]
Consider reimplementing if it did not cause a performance issue. To clarify, it's a big CID for UMTS/3G with combined RNCID and CID.
