### ISSUE TITLE
Ignore deleted towers/sectors in the band and region count calculation

### ISSUE THREAD

**Issue by veixes** [CellMapper/Cellmapper-Site#19]
For example, MNC 248-2 does not have B1 used in LTE (except one false reading)
Link back to map https://www.cellmapper.net/map?MCC=248&MNC=2&type=LTE&latitude=58.687928358691444&longitude=24.27145636716615&zoom=8&showTowers=true&clusterEnabled=false&tilesEnabled=true&heatMapEnabled=false&showOrphans=true&showFrequencyOnly=false&showBandwidthOnly=false&DateFilterType=FirstSeen&showHex=false&bands=1&showVerifiedOnly=false&showUnverifiedOnly=false&showLTECAOnly=false

But the count of known frequency sectors in brackets is (6984). This might be calculated from the false towers which had b1 reported as band, but were actually 3G towers.

Proposal is to ignore the counting the deleted towers/sectors in that view. Also, it would make sense to ignore deleted towers/sectors in the Region part calculation(brackets) also.

![image](https://cloud.githubusercontent.com/assets/22761625/21547254/8b305e4c-cded-11e6-9fa9-df01ec22c18f.png)

**Comment by zivan56** [comment]
It does not count deleted data, deleted data is actually deleted from cache tables from which this information is calculated.
