### ISSUE TITLE
Cannot move grouped BTS

### ISSUE THREAD

**Issue by marcoGardellini** [CellMapper/Cellmapper-Site#21]
It's impossible (or nearly) to move grouped BTS.... When several BTS are located on the same spot, you cannot move them individually.

Es https://www.cellmapper.net/map?MCC=222&MNC=10&type=LTE&latitude=45.65721296296771&longitude=13.779546588048124&zoom=21&showTowers=true&clusterEnabled=true&tilesEnabled=true&heatMapEnabled=false&showOrphans=true&showFrequencyOnly=false&showBandwidthOnly=false&DateFilterType=FirstSeen&showHex=false&bands=0,3,20&showVerifiedOnly=false&showUnverifiedOnly=true&showLTECAOnly=false&showBand=0

Screenshot:
https://s28.postimg.org/m0k29l8dp/bts.png

**Comment by olkitu** [comment]
Don't click, just only drag and drop tower to new position.
