### ISSUE TITLE
List (updated mothly) of Belgian Towers 

### ISSUE THREAD

**Issue by alinderom** [CellMapper/Cellmapper-Site#22]
Hi,
noticed a lot of towers of Belgium are missing. on the offcial site of the Belgian tower-regulator http://www.sites.bipt.be/ a list, that is updated monthly, can be found about the location of towers.
The actual link is http://www.sites.bipt.be/lijst-liste.xlsx
Maybe this can be used to place the location of the towers into CellMapper

**Comment by olkitu** [comment]
Data cannot add to CellMapper because not include location correct format, RSRP, ALT, Accuracy etc... There is our API info: https://docs.cellmapper.net/mw/index.php/CellMapper_API

**Comment by alinderom** [comment]
Thanks,
will it be enough to change the coordinates to a readable Longitude & Lattitute and have the country code of Belgium? Or are all the other fields manadatory?

**Comment by olkitu** [comment]
latitude, longitude, altitude, mcc, mnc , lac, cid, signal, type, subtype is mandatory.

**Comment by alinderom** [comment]
Thanks, the thuis list is indeed useless
The reason was i had the following problem
This is what CallMapper finds. the green crosses are where towers are
![afbeelding](https://cloud.githubusercontent.com/assets/25255092/22165675/5be210fa-df5d-11e6-8ea4-7e3dd940117f.png)
This is from the foficial site. The red croos is where CellMapper thinks the towers are, but the towersd are at the circels ont he bottom and top
![afbeelding](https://cloud.githubusercontent.com/assets/25255092/22165709/8930a936-df5d-11e6-9903-cb3c7299a124.png)

What is my problem : It is tower 83605 & 83593 that are wronly placed, but I don't knwo with which tower they correspond

**Comment by olkitu** [comment]
This map helps you locate tower when data is enough on CellMapper map. Because linked map not have Cell ID, we cannot use that to locate tower to correct place. 

So i recommended you or someone other user go to this area and save more data to Cellmapper to locate tower.

**Comment by alinderom** [comment]
Thanks for your help, I know what to do :)
