### ISSUE TITLE
remove the second "proximus"

### ISSUE THREAD

**Issue by alinderom** [CellMapper/Cellmapper-Site#23]
HI,
when choosing Belgium you have 2 numbers for proximus. Number 1 & 25. That's one to much we only have one Proximus in Belgium. According to the measurements the "1 proximus" is the correct one.
As you can see below number 25 only has 3G and 1 city

![afbeelding](https://cloud.githubusercontent.com/assets/25255092/22397026/10611f02-e568-11e6-8d3f-40ef8b657827.png)

**Comment by zivan56** [comment]
Completed.
