### ISSUE TITLE
"Only Show My Contributions" does not work anymore

### ISSUE THREAD

**Issue by alinderom** [CellMapper/Cellmapper-Site#24]
Hello,
on the cellmapper website you could filter the shwon measurements and towers by checking "Only Show My Contributions". This does not seem to we workign anymore. I have the impression it only filmters the "own" discovered towers, but shows "all" the measured points.
I think this still worked at the beginning of the week.

**Comment by olkitu** [comment]
I tested and working.

**Comment by alinderom** [comment]
Hi, Yesterday I also noticed that on the cell phone (version 5.0.8 & when showing MAP) all Contributions are also shown

**Comment by alinderom** [comment]
In attachment a view from this morning, the "only show my contributions" filter is on, and i see contributions in "Luik". A place where I have surely not been.

![2017-03-06 08_13_34-proximus belgium - cellular coverage and tower map](https://cloud.githubusercontent.com/assets/25255092/23600070/05ca0730-0245-11e7-8c4f-21fcd2ea7a56.png)

**Comment by zivan56** [comment]
This is normal, it only shows towers you have contributed to.

You cannot see what tiles you have contributed to, this would require terrabytes of data storage and infinately more processing power since they are millions of PNGs at each zoom level.

**Comment by alinderom** [comment]
Thanks, It's probably that untill now I have been to places that where unknown to cellmapper. I have been using "2G-only" in the months of february. Only few people seem to use 2G, and now-one seems to use cellmapper where I live.
