### ISSUE TITLE
Upload from cell phone does not work correctly

### ISSUE THREAD

**Issue by alinderom** [CellMapper/Cellmapper-Site#25]
I noticed some missed uploads when looking at the data points on the cellmapper website. 
Trying to upload form the cell phone only finds less than 100 points per day while there should be over 1000 (CSV file between 200 & 500 Kbytes).
Of course I could upload them by the computer but this way of working is not adviced by the website.
Question : what goes wrong? How to solve it?

PS: The CSV file of sunday 5 march 2017 contains 4000 lines, but when re-uploading that file only 71 are proposed.

**Comment by olkitu** [comment]
Since app version 5.0.9 have feature "Purge uploaded data", what automatic will clear local database when uploaded. But when you upload and server confirm that should all data uploaded correctly and all data is in database. 

You can also upload CSV to server if you like.

**Comment by alinderom** [comment]
I still have 5.0.8, I'll update tot 5.0.9 & upload the CSV through the website

**Comment by alinderom** [comment]
Hi, play.google.com only shows version 5.0.8, not 5.0.9

**Comment by olkitu** [comment]
Yes under BETA. Sorry, since 5.0.8 have auto purge feature (you see changelog on google play). That feature autopurge local database when you have uploaded... If you want disable that, you need join beta: https://play.google.com/apps/testing/cellmapper.net.cellmapper and then update to latest beta version.

**Comment by alinderom** [comment]
Hi, just activated my beta account. Thanks. I'll keep you informed of possible beta-issues

**Comment by olkitu** [comment]
It takes few minutes and you get notification when beta version available.

**Comment by zivan56** [comment]
You are most likely referring to neighbour data points. These are useless except for 2G GSM (not enough information), so they are discarded.

**Comment by alinderom** [comment]
Hi zivan56, what do you mean by "neighbour data points"? I have selected 3G on my cell phone.
This is what I noticed : yesterday I uploaded all my points of the evening (I always do a manual upload from my cellphone). All points where uploaded , but when looking on the website this morning I do not notice these points (points of loacations where no-one has gone before (sounds like star trek :) )

**Comment by zivan56** [comment]
Neighbour cells do not have enough information, and are discarded.  You can check your CSV and will notice they lack LAC/TAC/CID/etc.

**Comment by alinderom** [comment]
All my lines have this information, they only lack ARFCN as you can see in attachment (CSV renamed to TXT)
[signal-2017-03-05.txt](https://github.com/CellMapper/Cellmapper-Site/files/820422/signal-2017-03-05.txt)

**Comment by zivan56** [comment]
This is quite strange, CellMapper should not write -1 as an ARFCN.  What version of the app are you running?  I can forsee this causing issues.

**Comment by zivan56** [comment]
Also, how did you notice "missing uploads"?  Where did it indicate that they were missing?

**Comment by alinderom** [comment]
I have been looking at the Cellmapper website and i have not "seen" my contributions. As you can see in attachment. The red lines are locations where I have been yesterday and i don't see these contributions on the website
![2017-03-06 09_05_46-proximus belgium - cellular coverage and tower map](https://cloud.githubusercontent.com/assets/25255092/23601555/6ad5a29a-024c-11e7-954b-a6b9f051ffb4.png)

**Comment by alinderom** [comment]
I am running version 5.0.8 
I also have CSV files form 21 januari 2017 (don't know what version of the APP it was), and I also see" -1" when its a 3G-signal 
51.19184439,5.032839,71,206,1,3042,21399810,-114,LTE,LTE,,
51.19184449,5.03283886,71,206,1,3022,21399810,-103,UMTS,HSPA+,,-1
51.19184448,5.03283886,71,206,1,3022,21399810,-103,UMTS,HSPA+,,-1
51.19184425,5.03283894,68,206,1,3042,21402881,-111,LTE,LTE,,

**Comment by zivan56** [comment]
It can take up to a week for data to show, it won't show instantly. That doesn't indicate that the data did not upload. I don't see any way it can upload and dissapear since each ID is confirmed back from the server.

**Comment by alinderom** [comment]
Then you'll have to adapt the websiet. On https://www.taisto.org/Cellmapper/en you can read.
5. Upload your recorded data to the Cellmapper server by opening the Cell List tab and Upload and Statistics tab. You should always upload your newly measured base station so that somebody else won't have to go and redo it, and they can instead view it from the map. The cellmapper map is updated nearly instantaneously .

instantaneously is not "a week". My regular experience is a couple of hours.

I'll check it out.

**Comment by olkitu** [comment]
@alinderom It depends how busy server is, sometimes 5min, few hour to day. I think not a week but possible days...

**Comment by zivan56** [comment]
As stated, time to generation depends on load.
