### ISSUE TITLE
Cell phone does not go into standby

### ISSUE THREAD

**Issue by alinderom** [CellMapper/Cellmapper-Site#26]
When CellMapper is running and you want to turn off the screen of your cellphone, then the screens automatically comes up again (screen where you can give your login code/pasword).
Is this problem known? (I am having this in 5.0.8 & 5.0.9beta)

**Comment by olkitu** [comment]
What phone you have? And do you have API 4.2+ enabled and not have 'Keep screen on' option on?

**Comment by alinderom** [comment]
Samsung S4-mini (GT-I9195) with Android 4.4.2
The option "Use new Android 4.2 Cell ID..." is not activated since you state most manufacturers do not implement this.
The option "Keep screen ON" is in grey and is unchecked
The option "Keep screen on brightness" si also unchecked
Do you want me to use the "send debug info" option?

**Comment by olkitu** [comment]
Yes, on Samsung you cannot switch screen off because then Cell ID API not refresh. That is problem when using old API. So you must keep screen on, but you can use Blank screen on main menu.

**Comment by alinderom** [comment]
Do you suggest I use the "new Android 4.2 Cell ID" option. or does Samsung not spport this?

**Comment by olkitu** [comment]
@alinderom API 4.2+ not supported on Samsung because Samsung not implement this. Some Samsung maybe working, need test. More info here: https://docs.cellmapper.net/mw/index.php/Tested_Phones

**Comment by zivan56** [comment]
This also happens on CDMA, as it is required to measure proper signal strength.
