### ISSUE TITLE
contributes mesurements not visible, discovered towers visible

### ISSUE THREAD

**Issue by alinderom** [CellMapper/Cellmapper-Site#29]
I already mentioned that I had the impression that uploaded contributions were not visible. One of the proposed reasons was "it can take a couple of days before they are visible."
I went to a new place yesterday (see screenshot below). The red lines are the locations i drove . A place where no CellMapper has gone before. Below you can see the map : Note : contributor alin_derom (= me) . You also notice 2 new towers discoverd for the first time yesterday evening  (GMT +1 ). How do explain that the towers are visible but the measurment points are not visible? Are towers treated quicker than measured points?
PS : Notice that my missing points of sunday  (4 days ago) are still not visible(
![afbeelding](https://cloud.githubusercontent.com/assets/25255092/23765359/421a9754-0501-11e7-81be-8d3d848422a4.png)

The cooridnates of the location of 4 days ago are  https://www.google.be/maps/place/50%C2%B056'07.7%22N+5%C2%B020'49.9%22E/@50.935465,5.3449953,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d50.935465!4d5.347184

**Comment by zivan56** [comment]
Tiles vs. towers are generated at different times. There is a huge backlog as there was not generation for 2 days due to massive infrastructure upgrades.

**Comment by alinderom** [comment]
Thanks , that explains a lot.
Suggestion : have an information on the CellMapper website with the timestamp of the latest "tower processing time" and "measurements processing time".
