### ISSUE TITLE
Can't move towers for Provider 208-15-3G

### ISSUE THREAD

**Issue by cedricpah** [CellMapper/Cellmapper-Site#30]
Since December 2016, no cells could be moved as they must be.
They can be moved, but they appears as "non located towers" (in red) and the shape is not actualized consequently.

**Comment by zivan56** [comment]
Can you provide move details?  For certain network types?  Just your user?
Nobody else has reported such an issue.

**Comment by cedricpah** [comment]
Yes, it's only for UMTS towers. 
I will past a link for tower 8324 LAC 3800 for 208 15 3G.
It'is write placed, but there is no history (I try to move it many many time), It appears red (not green) and the "shape" is not generated. Maybe with your username it will be good ?
My username has no problem with other France networks.

Thank you very much.
So can you try to move this tower ?
[https://www.cellmapper.net/map?MCC=208&MNC=15&type=UMTS&latitude=49.34916706206872&longitude=2.5198374425811965&zoom=17&showTowers=true&clusterEnabled=false&tilesEnabled=true&heatMapEnabled=false&showOrphans=true&showFrequencyOnly=false&showBandwidthOnly=false&DateFilterType=FirstSeen&showHex=false&bands=0,1,8,10&showVerifiedOnly=false&showUnverifiedOnly=false&showLTECAOnly=false&showBand=0](https://www.cellmapper.net/map?MCC=208&MNC=15&type=UMTS&latitude=49.34916706206872&longitude=2.5198374425811965&zoom=17&showTowers=true&clusterEnabled=false&tilesEnabled=true&heatMapEnabled=false&showOrphans=true&showFrequencyOnly=false&showBandwidthOnly=false&DateFilterType=FirstSeen&showHex=false&bands=0,1,8,10&showVerifiedOnly=false&showUnverifiedOnly=false&showLTECAOnly=false&showBand=0)

**Comment by zivan56** [comment]
Please give it a try now.
It was due to a very special formula being used for this provider only..

**Comment by cedricpah** [comment]
Thank you very much, it works again !
