### ISSUE TITLE
question for translation

### ISSUE THREAD

**Issue by alinderom** [CellMapper/Cellmapper-Site#31]
Hi,
I started the translation in Dutch. I have always had trouble in the APP with the meaning of next part : 
**Enable live uploading to the CellMapper website. This will use data, but ensure the most accurate results are reported\nYou can always upload recorded data at a later date**
As far as I know enabling "live upload" or "uploading manually later on" gave the same information and details. The only difference was that the information is sent at a later time, and therefore not directly available for other users. 
In that case the original English phrase could be :  
**Enable live uploading to the CellMapper website. This will use data, but ensure the most recent measurements are reported\nYou can always upload recorded data at a later date**

**Comment by zivan56** [comment]
When you enable live upload, it uses data.  This triggers UMTS to go into HSPA+/DC-HSPA+ mode if fast-dormancy is used.  Likewise, LTE Carrier Aggregation if LTE is used.  So the statement still stands true.

**Comment by alinderom** [comment]
So when live update is used there is extra Cell-information that is collected, saved into the local DB and sent to CellMapper?

**Comment by zivan56** [comment]
Not more but the correct network subtype, especially for GSM/UMTS/CDMA

**Comment by alinderom** [comment]
OK Thanks
