### ISSUE TITLE
Warning DATA is not recorded

### ISSUE THREAD

**Issue by alinderom** [CellMapper/Cellmapper-Site#33]
Hi a suggestion : 
In CellMapper you can decide not to record any of the signals. In that case in the "Cell screen" the record icon is Red
In settings you can decide not to record 2G or 3G or 4G or any combination.
If you forgot this (or did it by accident) you can have the impression that you record (green record icon) but you are actually not recording since in Setting that bandwidth is excluded. Especillay when during the trip the bandwidth changes this can be unwanted.

Suppose that in SETTINGS the 3G recording is OFF
When recording is OFF is is Red (actual situation
When recording in ON and you are connected in 2G or 4G the icon is GREEN (actual situation)
When recording is ON and you are connected in 3G (which is excluded in the setings) then the icon could be ORANGE (in teh actual situation it is still GREEN°

So Suggestion : show an ORANGE icon when recording is ON and you are connected with a bandtwith that is excluded in the settings

**Comment by brycenesbitt** [comment]
This sounds good.
I'll add it would be nice in "map mode" to have a copy of the recording icon (whatever the state: on / off / partially on ).

**Comment by zivan56** [comment]
I don't see any way to detect this.

You could have any combination of:
2/3/4G reported at same time from RIL (neighbours, handover, etc)
Dual SIM phones with multiple RATs reporting as connected
CDMA SVLTE phones with both 2G and 4G always connected

This will result in a horrible user experiance of that icon constantly changing, making it confusing to most users.  There is a tiny percentage of users that restricts RAT recording, and it is an advanced feature that should be used with caution.
