### ISSUE TITLE
Solution for long lines

### ISSUE THREAD

**Issue by alinderom** [CellMapper/Cellmapper-Site#34]
When you look the attachment you can see that some titles are not shown completely on the screen.
Can you find a solution so that the complete titels can be read?

![screenshot_2017-03-24-15-30-16 1](https://cloud.githubusercontent.com/assets/25255092/24298748/41fc7d30-10a7-11e7-96a2-018f4d0c447f.png)

**Comment by zivan56** [comment]
Your phone resolution is quite low. If you turn your phone sideways it should display the full titles.

**Comment by alinderom** [comment]
My phone is a Samsung S4-mini with resolution 540 x 960 pixels
I know it is readable by turning the phone, but a smaller font size could also help :)
