### ISSUE TITLE
Feature request: click a green dot to see which tower(s) it belongs to

### ISSUE THREAD

**Issue by adlr** [CellMapper/Cellmapper-Site#37]
Hi, sometimes I see signal dots that are green, but don't seem to be assigned to any tower. For example, there is one at approximately 2104 Ticonderoga Dr, San Mateo, CA 94402, USA, which I don't see enclosed in any region for any nearby tower.

The usual way I can figure these out is by going to that place and checking my phone, but the data surely is in the cell mapper database and it would be great to show it on the site.

Thanks!

**Comment by olkitu** [comment]
Tower might be removed on map, we do not yet method tower and signal dots removed also... also if you record only one points of tower, tower will not showed on map but it shows signal dots.  Reason because we trying filtering incorrect cell data on our map.

**Comment by brycenesbitt** [comment]
Could I select a group of signal dots, and see all the towers they came from (or a note the tower is deleted)?

**Comment by zivan56** [comment]
The signal dots (made up of slippy tiles) are millions of PNG files, they have no association with a tower.
