### ISSUE TITLE
Tower center fooled by far off data point

### ISSUE THREAD

**Issue by brycenesbitt** [CellMapper/Cellmapper-Site#38]
Have a look at this map.  The center of the bright green area is a tower, eNB ID #94696.
Cellmaper has this tower some distance away.

Perhaps Cellmaper could discard scattered data points, when there is a sufficient cluster of points?

![image](https://user-images.githubusercontent.com/1294423/27983043-5720edcc-6368-11e7-9015-515dd7804d9d.png)

**Comment by olkitu** [comment]
Calculation is not 100% accurate but you can login to site when you record data and move tower (marker) to correct position

**Comment by zivan56** [comment]
It already does calculations by using percentiles for maximum distances and other methods.  Ultimately, a large number of false data points, TA readings, etc. will cause this from time to time...it is not an exact science.

I believe from the other thread, you are using quite a Samsung device, which are notorious for bad Android API implementations which cause a large number of false data points to be reported.

**Comment by zivan56** [comment]
Removing TA from the calculation should have improved this significantly.
