### ISSUE TITLE
Right click to "select provider" does not work on Asus R11 Chromebook on Chrome

### ISSUE THREAD

**Issue by brycenesbitt** [CellMapper/Cellmapper-Site#39]
On Firefox/Desktop Chrome or Safari I can click to get a cell provider list, sorted by popularity.
This menu hardly ever, if at all, will come up on a Chromebook R11.  Instead a little hand comes up that allows dragging the screen.

The Chrome Developer Tools/Javascript console is silent at this time (no errors, no warnings).
Version 59.0.3071.91 (Official Build) (64-bit) Chrome OS

**Comment by olkitu** [comment]
Old map we do not anymore update. It's very old as u see so better make new map :)

We started new map: https://github.com/CellMapper/Map-BETA

**Comment by zivan56** [comment]
Does Shift+click work?  Seems to be a common problem with Chromebooks from what I read online.  Ultimately, there is nothing OS specific on the map, and I do develop it using Chrome, which is what runs on the Chromebook.
