### ISSUE TITLE
[Android] Left and right paddings of main activity

### ISSUE THREAD

**Issue by RistiCore** [CellMapper/Cellmapper-Site#53]
Left and right padding of main application activity should be increased to prevent text from rubbing into the edges.

![image](https://user-images.githubusercontent.com/41734461/55676597-c4d93a80-58e0-11e9-8ff8-bd823ef55e64.png)

**Comment by jk-5** [comment]
This is an issue especially with phones with a curved screen like the samsung S8 or S9. Would be really nice to increase this a few pixels

**Comment by olkitu** [comment]
@RistiCore  This is wrong place for this issue, please report to https://github.com/CellMapper/CellMapper-Android-App/issues project about this.
