### ISSUE TITLE
Google Maps API Not Working -> Replaced to OpenStreetMap

### ISSUE THREAD

**Issue by lightspeed2398** [CellMapper/Cellmapper-Site#54]
Message regarding Web Map: 

 PLEASE FIND TEMPORARY WORKAROUND AT : https://www.cellmapper.net/testmap/bmap 

Due to an unexpected surge in traffic and new quotas imposed on CellMapper by our Web Map supplier (Google) usage of the Web Map is currently disrupted until further notice. We have been testing a replacement solution to prevent this from happening, but it is not yet ready for live usage, we expect this to be the case soon however. I appreciate that this isn't the high service quality and reliability that you've all come to know and love from CellMapper but we ask for a small amount of patience while we get this sorted and as usual we apologise for the disruption, inconvenience and distress. Any questions to the moderators please. 

Your CM Team

**Comment by olkitu** [comment]
Google Map is now replaced to OSM Map

**Comment by RistiCore** [comment]
Error on tower movement attempt:

> An error occured:
> Error performing override

**Comment by RAviraniii** [comment]
Do you plan to move to Bing Maps permanently?  Google Maps' satellite view is significantly better than Bing Maps'...switching to Bing Maps could make it a lot harder to locate cell sites.

**Comment by jamespole** [comment]
Google Maps's satellite view isn't always the best. I'm hoping instead of going back to Gmaps, that CellMapper look at providing satellite views from a variety of providers. ESRI is very good for my part of the world for example.

**Comment by pivirani** [comment]
In the US, Google Maps has the best Satellite view by a large margin (both in terms of image quality and age of imagery).  I think options would be nice though.

**Comment by olkitu** [comment]
> Do you plan to move to Bing Maps permanently? Google Maps' satellite view is significantly better than Bing Maps'...switching to Bing Maps could make it a lot harder to locate cell sites.

Google Satellite is part of Google Maps API so for now there is no way really implement it.

**Comment by DanPFW** [comment]
This is unfortunate.  This map has lost a lot of it's usage with no satellite imagery.  The new Pins (circles) are very large and touchy.  Just touching them asks if you want to move them,  Without an ability to upload/download cell site information and coordinates, it will be next to impossible to set the pins correctly.

**Comment by nelsonjw1** [comment]
> This is unfortunate.  This map has lost a lot of it's usage with no satellite imagery.  The new Pins (circles) are very large and touchy.  Just touching them asks if you want to move them,  Without an ability to upload/download cell site information and coordinates, it will be next to impossible to set the pins correctly.

I agree completely. The beta map (Bing) is a little better, but is limited in usefulness due to lacking many of the filters (including date) of the main map.  Big step backward at this point. I understand it was necessary due to the Google API limits, but it's still a step backward function-wise.

**Comment by gially86** [comment]
Hi, it's not possibile to move on correct position towers without any satellite map help, so if you have no intention to restore Google Maps API, in my opinion you can also close your project

**Comment by jamespole** [comment]
@gially86: There are other satellite providers already in use in the BETA map which I have been using the last few days with no issues. It is no longer worth using Google as they charge too much for access to their API—there are other free/reasonable priced options. This is not the only project to run into issues with Google, many others (even large companies and organisations) have had to move away from Google to other mapping providers due to the huge prices Google asks for.

**Comment by olkitu** [comment]
> Error on tower movement attempt:
> 
> > An error occured:
> > Error performing override

This issue fixed yesterday on map.

**Comment by lightspeed2398** [comment]
> Hi, it's not possibile to move on correct position towers without any satellite map help, so if you have no intention to restore Google Maps API, in my opinion you can also close your project

Hi gially86, maybe you can not locate towers without using satellite but there are many talented mappers who feel able to. This change was forced upon us by Google and we plan to add more functionality over the course of time once we have sorted out fully the stability of our new map. It may be your opinion that we should shut CellMapper down but we tend not to act in such dramatic and hyperbolic terms instead preferring a more calm and rational look on this, if you don't want to use CellMapper then that is your decision but I see no need to force that onto other users.

**Comment by lightspeed2398** [comment]
> where I can find BETA map?

In the link in the description, which maybe you should have read before asking.

**Comment by lightspeed2398** [comment]
> > @gially86: There are other satellite providers already in use in the BETA map which I have been using the last few days with no issues. It is no longer worth using Google as they charge too much for access to their API—there are other free/reasonable priced options. This is not the only project to run into issues with Google, many others (even large companies and organisations) have had to move away from Google to other mapping providers due to the huge prices Google asks for.
> 
> I agree, the beta map seems to be working well with its selection of several map engines. But it is missing several filters including filtering by date which seems to be an important/basic feature, which really limits its usefulness. I assume that this can and will be fixed, but in the meantime due to the issues with the OpenStreetMap version there is some lost functionality.
> 
> As an IT Director at work I do understand the issue with Google Maps; it's a decision I have to review with each project now to determine whether it's cost effective.

Hi, 

Yeah it's a bit of an issue but I would caution on relying too much on the testmap, which is a test environment at most, which is not focused on by regular users, we had no intention to make it so widely used and it simply not going to receive the same level of support as the normal map with OSM using OpenLayers at the normal address. It's very annoying what Google have done but it is what it is and we'll try and make the best of it to fix the issues that have arisen. We were forced to switch a little earlier than we would have liked but we're going to be rapidly improving the issues that people find. The key thing is that we know about them and we're given the room to fix them. 

Cheers, 

LS

**Comment by gially86** [comment]
> > where I can find BETA map?
> 
> In the link in the description, which maybe you should have read before asking.

Nope, I have found it on FAQ

**Comment by pivirani** [comment]
Is there any chance you guys will add more ads and revert to Google Maps?  I would be very happy to see a few more ads if we could get a large amount of functionality back...

**Comment by olkitu** [comment]
> Is there any chance you guys will add more ads and revert to Google Maps? I would be very happy to see a few more ads if we could get a large amount of functionality back...

Mostly people use adblock so there is no point add more advertisement to map.

Some functionally missing but coming to OSM map - we working on these.

**Comment by olkitu** [comment]
![image](https://user-images.githubusercontent.com/10426342/57748707-c10cb500-76e3-11e9-99a6-aa5223c6cfe9.png)

Bing Satellite, Bing Road and Bing Grayscale Maps is not available - on left side menu you can change map type.
