### ISSUE TITLE
Google Maps: right-click link doesn't work properly

### ISSUE THREAD

**Issue by eutill** [CellMapper/Cellmapper-Site#57]
Hi,
I have noticed a broken link: when right clicking in the current CM map and selecting 'Open in Google Maps', it leads me to Google Maps without setting the right location.
This is because the selected link
`https://www.google.com/maps?@[lat],[lon],[zoom]z`
is not correct. Instead, it should read
`https://www.google.com/maps/@[lat],[lon],[zoom]z`,
that is, replacing the `?` with `/`.

Best regards and thank you for the good work!
eutill

**Comment by olkitu** [comment]
Thank you for reporting this issue. I fixed this issue now.
