### ISSUE TITLE
Drag to move tower not working with new OSM/Bing map

### ISSUE THREAD

**Issue by brycenesbitt** [CellMapper/Cellmapper-Site#59]
# Your Browser Detail
* Browser: Google Chrome 57.0 Windows

# Steps to reproduce

At this point, I am trying to move a tower, but nothing happens with the new map.
I've tried all the base maps, same result.

https://www.cellmapper.net/map?MCC=311&MNC=480&type=CDMA&latitude=44.725543889519344&longitude=-116.42965321744478&zoom=15&showTowers=true&showTowerLabels=false&clusterEnabled=true&tilesEnabled=true&showOrphans=false&showNoFrequencyOnly=false&showFrequencyOnly=false&showBandwidthOnly=false&DateFilterType=Last&showHex=false&showVerifiedOnly=false&showUnverifiedOnly=false&showLTECAOnly=false&showBand=0&mapType=bing_street&showSectorColours=true

**Comment by olkitu** [comment]
Click first this tower and then drag and drop to new location. Tested and works

**Comment by brycenesbitt** [comment]
Click then move works.
Direct drag does not.
