### ISSUE TITLE
Older contributions don't show

### ISSUE THREAD

**Issue by CastOfficial** [CellMapper/Cellmapper-Site#62]
# Your Browser Detail

* Browser: Google Chrome 80.0.3987.132 Windows

# Steps to reproduce

1) select a tower
2) click on one of the contributors (that has contributed more than 20 times)
3) Click the previous button

# Current behavior

Shows the same history, and doesn't show older contribs

# Expected behavior

Show contributions that happened longer ago

# Video/Screenshot link (optional)

https://imgur.com/a/TfegTj7

Apologies if this has already been posted, I looked substantially to make sure this hasn't been.

**Comment by olkitu** [comment]
I think there is no older contributions. You can scroll list down to see all.

**Comment by CastOfficial** [comment]
I've tried this on my account which has located over 100, don't see anything, same for others.

**Comment by CastOfficial** [comment]
Are you able to reproduce?

**Comment by olkitu** [comment]
You have to click NEXT to see older contributions.

**Comment by CastOfficial** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️ Sorry
