### ISSUE TITLE
Map is not usable on 4k displays as marker labels scale incorrectly

### ISSUE THREAD

**Issue by jeffreykog** [CellMapper/Cellmapper-Site#65]
# Your Browser Detail
Browser: Firefox 78.0.2
OS: Ubuntu 20.04

# Steps to reproduce
Open the map on a 4k monitor and pan the map

# Current behavior
The labels have the correct size on the initial draw, but when the map is panned, the labels are too big

# Expected behavior
Labels always have the size like on the initial paint

# Video/Screenshot link (optional)
![Screenshot from 2020-07-29 19-36-15](https://user-images.githubusercontent.com/1783250/88833763-1347d200-d1d3-11ea-9b5c-36d474e18af6.png)

On the top, you see one label that still has the correct size from the initial paint (site 23200). The other labels were dragged into the viewport, giving them the incorrect size.

**Comment by olkitu** [comment]
Is this relevant issue anymore?

Works fine on my Ubuntu 20.04 LTS + 2K screen and Firefox browser. Also tested works fine with Chrome.

**Comment by jeffreykog** [comment]
No, it seems to have been fixed recently. Closing this issue. Thanks!
