### ISSUE TITLE
CellMapper Database as JSON File

### ISSUE THREAD

**Issue by iDustbin** [CellMapper/Cellmapper-Site#67]
# Your Browser Detail

* Browser: Google Chrome 9x / MacOS

# Current behavior
Hi, im looking for all your CellInformations as a Database or Flatfile like .json,
is your dataset public available ?

**Comment by olkitu** [comment]
CellMapper doesn't offer any exports: https://cellmapper.freshdesk.com/support/solutions/articles/28000002032-is-possible-export-tower-and-tiles-data-on-map-
